openapi: 3.0.3
info:
  title: CloudSDK Equipment Gateway API
  description: APIs that provide services for delivering notifications and commands to the equipment.
  version: 1.0.0
servers:
  - url: https://localhost:9091
    description: Local Dev server
    
tags:
- name: Equipment Gateway
    
components:
  securitySchemes:
    tip_wlan_ts_auth:
      type: http
      scheme: bearer
      
  responses:
    GenericApiError:
      description: this object is returned in the cases when an API throws an exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JsonSerializedException'
            
  schemas:
    
#
#Generic data models used for many APIs
#
    GenericResponse:
      properties:
        message:
          type: string
        success:
          type: boolean
          
    JsonSerializedException:
      description: this object is returned in the cases when an API throws an exception
      properties:
        exType:
          type: string
          enum:
            - IllegalStateException
        error:
          description: error message
          type: string
        path:
          description: API path with parameters that produced the exception
          type: string
        timestamp:
          description: time stamp of when the exception was generated
          type: integer
          format: int64
          
#
# Objects related to Equipment Gateway
#

    CEGWCommandResultCode:
      type: string
      enum:
      - Success
      - NoRouteToCE
      - FailedToSend
      - TimedOut
      - FailedOnCE
      - UnsupportedCommand
      
    PortalUserRole:
      type: string
      enum:
      - SuperUser
      - SuperUser_RO
      - CustomerIT
      - CustomerIT_RO
      - TechSupport
      - TechSupport_RO
      - Public
      
    CEGWCommandType:
      type: string
      enum:
      - ConfigChangeNotification
      - CloseSessionRequest
      - CheckRouting
      - BlinkRequest
      - ChangeRedirectorHost
      - StartDebugEngine
      - StopDebugEngine
      - FirmwareDownloadRequest
      - FirmwareFlashRequest
      - RadioReset
      - RebootRequest
      - ClientBlocklistChangeNotification
      - NewChannelRequest      
      
    CEGWBaseCommand:
      properties:
        equipmentId:
          type: integer
          format: int64
        inventoryId:
          type: string
        userName:
          type: string
        userRole:
          $ref: '#/components/schemas/PortalUserRole'
          
      
    EquipmentCommandResponse:
      properties:
        resultCode:
          $ref: '#/components/schemas/CEGWCommandResultCode'
        resultDetail:
          type: string
        command:
          $ref: '#/components/schemas/CEGWCommand'
        gatewayHost:
          type: string
          description: host of the gateway that processed the command
        gatewayPort:
          type: integer
          format: int32
          description: port of the gateway that processed the command

    
    CEGWCommand:
      oneOf:
        - $ref: '#/components/schemas/CEGWConfigChangeNotification'
        - $ref: '#/components/schemas/CEGWCloseSessionRequest'
        - $ref: '#/components/schemas/CEGWRouteCheck'
        - $ref: '#/components/schemas/CEGWBlinkRequest'
        - $ref: '#/components/schemas/CEGWChangeRedirectorHost'
        - $ref: '#/components/schemas/CEGWStartDebugEngine'
        - $ref: '#/components/schemas/CEGWStopDebugEngine'
        - $ref: '#/components/schemas/CEGWFirmwareDownloadRequest'
        - $ref: '#/components/schemas/CEGWFirmwareFlashRequest'
        - $ref: '#/components/schemas/CEGWRadioResetRequest'
        - $ref: '#/components/schemas/CEGWRebootRequest'
        - $ref: '#/components/schemas/CEGWClientBlocklistChangeNotification'
        - $ref: '#/components/schemas/CEGWNewChannelRequest'
      discriminator:
        propertyName: model_type


    ChannelPerRadio:
      properties:
        is5GHz:
          type: integer
          format: int32
        is2dot4GHz:
          type: integer
          format: int32
        is5GHzU:
          type: integer
          format: int32
        is5GHzL:
          type: integer
          format: int32
      
      
    CEGWNewChannelRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - NewChannelRequest
        model_type:
          type: string
          enum:
          - CEGWNewChannelRequest
        newPrimaryChannels:
          $ref: '#/components/schemas/ChannelPerRadio'
        newBackupChannels:
          $ref: '#/components/schemas/ChannelPerRadio'

    MacAddress:
      type: object
      properties:
        model_type:
          type: string
          enum:
          - MacAddress
        addressAsString:
          type: string

    CEGWClientBlocklistChangeNotification:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - ClientBlocklistChangeNotification
        model_type:
          type: string
          enum:
          - CEGWClientBlocklistChangeNotification
        blockList:
          type: array
          items:
            $ref: '#/components/schemas/MacAddress'

    CEGWRebootRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - RebootRequest
        model_type:
          type: string
          enum:
          - CEGWRebootRequest
        useInactiveBank:
          type: boolean
          description: Swap the bank during reboot
        performReset:
          type: string
          enum:
           - NoReset
           - ConfigReset
           - FactoryReset

    CEGWRadioResetRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - RadioReset
        model_type:
          type: string
          enum:
          - CEGWRadioResetRequest
        radio:
          type: string
          enum:
           - is5GHz
           - is2dot4GHz
           - is5GHzU
           - is5GHzL
        resetMethod:
          type: string
          enum:
           - init
           - reload


    CEGWFirmwareFlashRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - FirmwareFlashRequest
        model_type:
          type: string
          enum:
          - CEGWFirmwareFlashRequest
        firmwareVersion:
          type: string
    
    CEGWFirmwareDownloadRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - FirmwareDownloadRequest
        model_type:
          type: string
          enum:
          - CEGWFirmwareDownloadRequest
        firmwareVersion:
          type: string
        filePath:
          type: string

    CEGWStopDebugEngine:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - StopDebugEngine
        model_type:
          type: string
          enum:
          - CEGWStopDebugEngine

    CEGWStartDebugEngine:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - StartDebugEngine
        model_type:
          type: string
          enum:
          - CEGWStartDebugEngine
        gatewayHostname:
          type: string
          description: host of the remote ssh gateway to connect to
        gatewayPort:
          type: integer
          format: int32
          description: port of the remote ssh gateway to connect to

    CEGWChangeRedirectorHost:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - ChangeRedirectorHost
        model_type:
          type: string
          enum:
          - CEGWChangeRedirectorHost
        redirectorHost:
          type: string

    LEDColour:
      type: string
      enum:
        - blue
        - green
        - red
        - yellow
        - purple
        - cyan
        - white
        - off

    CEGWBlinkRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - BlinkRequest
        model_type:
          type: string
          enum:
          - CEGWBlinkRequest
        colour1:
          $ref: '#/components/schemas/LEDColour'
        colour2:
          $ref: '#/components/schemas/LEDColour'
        colour1DurationMs:
          type: integer
          format: int32
        colour2DurationMs:
          type: integer
          format: int32
        numCycles:
          type: integer
          format: int32
      example: 
        equipmentId: 1
        inventoryId: inv-1
        model_type: CEGWBlinkRequest
        commandType: BlinkRequest
        colour1: blue
        colour2: red
        colour1DurationMs: 1000
        colour2DurationMs: 1000
        numCycles: 3
        

    CEGWConfigChangeNotification:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - ConfigChangeNotification
        model_type:
          type: string
          enum:
          - CEGWConfigChangeNotification
      example: 
        equipmentId: 1
        inventoryId: inv-1
        model_type: CEGWConfigChangeNotification
        commandType: ConfigChangeNotification
        
    CEGWCloseSessionRequest:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - CloseSessionRequest
        model_type:
          type: string
          enum:
          - CEGWCloseSessionRequest
      example: 
        equipmentId: 1
        inventoryId: inv-1
        model_type: CEGWCloseSessionRequest
        commandType: CloseSessionRequest
        
    CEGWRouteCheck:
      allOf:
      - $ref: '#/components/schemas/CEGWBaseCommand'
      properties:
        commandType:
          type: string
          enum:
          - CheckRouting
        model_type:
          type: string
          enum:
          - CEGWRouteCheck
      example: 
        model_type: CEGWRouteCheck
        commandType: CheckRouting
        


## ---------------------------------------------------------------------------
security:
 - tip_wlan_ts_auth: []
paths:
 
  /api/commands:
    post:
      tags:
        - Equipment Gateway
      summary: Deliver commands to equipment gateway, which in turn will perform an operation for specified equipment
      operationId: sendCommands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CEGWCommand'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EquipmentCommandResponse'
        500: 
          $ref: '#/components/responses/GenericApiError'
